[[headers]]
for = "/*.woff"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "font/woff"

[[headers]]
for = "/*.woff2"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "font/woff2"

[[headers]]
for = "/*.eot"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/vnd.ms-fontobject"

[[headers]]
for = "/*.ttf"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "font/ttf"

[[headers]]
for = "/*.svg"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "image/svg+xml"
