/*.woff
    Access-Control-Allow-Origin: *
    Content-Type: font/woff
    
/*.woff2
    Access-Control-Allow-Origin: *
    Content-Type: font/woff2

    
/*.eot
	Access-Control-Allow-Origin: *
	Content-Type: application/vnd.ms-fontobject

/*.ttf
	Access-Control-Allow-Origin: *
	Content-Type: font/ttf
	
/*.svg
	Access-Control-Allow-Origin: *
	Content-Type: image/svg+xml